# Generated by Django 3.0.7 on 2020-06-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutacja', '0002_formucznia_uzytkownik'),
    ]

    operations = [
        migrations.AddField(
            model_name='formucznia',
            name='ukonczona_szkola',
            field=models.CharField(choices=[('LO', 'Liceum Ogólnokształcące'), ('ZSZ', 'Zasadnicza Szkoła Zawodowa'), ('BS1', 'Branżowa Szkoła I stopnia'), ('SP', 'Szkoła Podstawowa')], default='LO', max_length=3),
            preserve_default=False,
        ),
    ]
