# Generated by Django 3.0.7 on 2020-06-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutacja', '0003_formucznia_ukonczona_szkola'),
    ]

    operations = [
        migrations.AddField(
            model_name='formucznia',
            name='rok_ukonczenia',
            field=models.IntegerField(default=2020, max_length=4),
        ),
    ]
