# Generated by Django 3.0.7 on 2020-06-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutacja', '0004_formucznia_rok_ukonczenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='formucznia',
            name='pesel',
            field=models.IntegerField(default=0, max_length=9),
            preserve_default=False,
        ),
    ]
