# Generated by Django 3.0.7 on 2020-06-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutacja', '0006_auto_20200625_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='formucznia',
            name='miejsce_urodzenia',
            field=models.CharField(default='nieznane', max_length=200),
            preserve_default=False,
        ),
    ]
