# Generated by Django 3.0.7 on 2020-06-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutacja', '0008_formucznia_wojewodztwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formucznia',
            name='ukonczona_szkola',
            field=models.CharField(max_length=3),
        ),
    ]
