# Generated by Django 3.0.7 on 2020-06-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutacja', '0009_auto_20200625_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formucznia',
            name='rok_ukonczenia',
            field=models.IntegerField(default=2020),
        ),
    ]
