# Generated by Django 3.0.7 on 2020-06-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutacja', '0011_auto_20200625_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='formucznia',
            name='kod_pocztowy',
            field=models.CharField(default='00-001', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formucznia',
            name='miejscowosc',
            field=models.CharField(default='miejscowosc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formucznia',
            name='nr_domu',
            field=models.CharField(default=99, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formucznia',
            name='nr_lokalu',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formucznia',
            name='poczta',
            field=models.CharField(default='poczta', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formucznia',
            name='ulica',
            field=models.CharField(default='ulica', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formucznia',
            name='wojewodztwo_ur',
            field=models.CharField(default='MP', max_length=100),
            preserve_default=False,
        ),
    ]
