# Generated by Django 3.0.7 on 2020-06-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutacja', '0012_auto_20200625_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formucznia',
            name='nr_lokalu',
            field=models.IntegerField(null=True),
        ),
    ]
