# Generated by Django 3.0.7 on 2020-06-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutacja', '0013_auto_20200625_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='formucznia',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
