# Generated by Django 3.0.7 on 2020-06-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutacja', '0015_auto_20200626_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='formucznia',
            name='czy_ojciec',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formucznia',
            name='ojciec_imie',
            field=models.CharField(default='Imie', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formucznia',
            name='ojciec_nazwisko',
            field=models.CharField(default='Nazwisko', max_length=80),
            preserve_default=False,
        ),
    ]
